//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GetServerInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetServerInfoService.IGetServerInfo")]
    public interface IGetServerInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetServerInfo/GetServerTime", ReplyAction="http://tempuri.org/IGetServerInfo/GetServerTimeResponse")]
        string GetServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetServerInfo/GetServerName", ReplyAction="http://tempuri.org/IGetServerInfo/GetServerNameResponse")]
        string GetServerName();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetServerInfoChannel : Client.GetServerInfoService.IGetServerInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServerInfoClient : System.ServiceModel.ClientBase<Client.GetServerInfoService.IGetServerInfo>, Client.GetServerInfoService.IGetServerInfo {
        
        public GetServerInfoClient() {
        }
        
        public GetServerInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetServerInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServerInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServerInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        public string GetServerName() {
            return base.Channel.GetServerName();
        }
    }
}
